language: python
python:
  - "2.7"
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov
# command to run tests
script:
  - python setup.py develop
  - pytest --cov .

after_success:
  - codecov
