#!/usr/bin/env python

import rospy

from std_msgs.msg import Bool, Empty, String


class PythonNode(object):
    """This is a test node for python interfaces"""

    def __init__(self):
        rospy.init_node('python_syntax_test_node')

        self.sub1 = rospy.Subscriber("topic1", Bool, self.sub_cb1)

        # This is a comment for sub2
        self.sub2 = rospy.Subscriber("topic2", Bool, callback=self.sub_cb2)

        self.sub3 = rospy.Subscriber("topic3", Bool, self.sub_cb3, None)

        rospy.spin()

    def sub_cb1(self, msg):
        pass
    def sub_cb2(self, msg):
        pass
    def sub_cb3(self, msg):
        pass

if __name__ == '__main__':
    PythonNode()

